# Generated by Django 4.2.8 on 2024-01-09 00:08

import arvelloapp.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(blank=True, max_length=200, null=True)),
                ('addressLine1', models.CharField(blank=True, max_length=200, null=True)),
                ('province', models.CharField(blank=True, choices=[('ZAGREBAČKA ŽUPANIJA', 'ZAGREBAČKA ŽUPANIJA'), ('KRAPINSKO-ZAGORSKA ŽUPANIJA', 'KRAPINSKO-ZAGORSKA ŽUPANIJA'), ('SISAČKO-MOSLAVAČKA ŽUPANIJA', 'SISAČKO-MOSLAVAČKA ŽUPANIJA'), ('KARLOVAČKA ŽUPANIJA', 'KARLOVAČKA ŽUPANIJA'), ('VARAŽDINSKA ŽUPANIJA', 'VARAŽDINSKA ŽUPANIJA'), ('KOPRIVNIČKO-KRIŽEVAČKA ŽUPANIJA', 'KOPRIVNIČKO-KRIŽEVAČKA ŽUPANIJA'), ('BJELOVARSKO-BILOGORSKA ŽUPANIJA', 'BJELOVARSKO-BILOGORSKA ŽUPANIJA'), ('PRIMORSKO-GORANSKA ŽUPANIJA', 'PRIMORSKO-GORANSKA ŽUPANIJA'), ('LIČKO-SENJSKA ŽUPANIJA', 'LIČKO-SENJSKA ŽUPANIJA'), ('VIROVITIČKO-PODRAVSKA ŽUPANIJA', 'VIROVITIČKO-PODRAVSKA ŽUPANIJA'), ('POŽEŠKO-SLAVONSKA ŽUPANIJA', 'POŽEŠKO-SLAVONSKA ŽUPANIJA'), ('BRODSKO-POSAVSKA ŽUPANIJA', 'BRODSKO-POSAVSKA ŽUPANIJA'), ('ZADARSKA ŽUPANIJA', 'ZADARSKA ŽUPANIJA'), ('OSJEČKO-BARANJSKA ŽUPANIJA', 'OSJEČKO-BARANJSKA ŽUPANIJA'), ('ŠIBENSKO-KNINSKA ŽUPANIJA', 'ŠIBENSKO-KNINSKA ŽUPANIJA'), ('VUKOVARSKO-SRIJEMSKA ŽUPANIJA', 'VUKOVARSKO-SRIJEMSKA ŽUPANIJA'), ('SPLITSKO-DALMATINSKA ŽUPANIJA', 'SPLITSKO-DALMATINSKA ŽUPANIJA'), ('ISTARSKA ŽUPANIJA', 'ISTARSKA ŽUPANIJA'), ('DUBROVAČKO-NERETVANSKA ŽUPANIJA', 'DUBROVAČKO-NERETVANSKA ŽUPANIJA'), ('MEĐIMURSKA ŽUPANIJA', 'MEĐIMURSKA ŽUPANIJA'), ('GRAD ZAGREB', 'GRAD ZAGREB'), ('INOZEMSTVO / NIJE PRIMJENJIVO', 'INOZEMSTVO / NIJE PRIMJENJIVO')], max_length=100)),
                ('postalCode', models.CharField(blank=True, max_length=5, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=40, null=True, validators=[arvelloapp.models.validate_phone_number])),
                ('emailAddress', models.CharField(blank=True, max_length=100, null=True)),
                ('clientUniqueId', models.CharField(blank=True, max_length=4, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Idetifikacijski broj klijenta mora sadržavati točno 4 broja.')])),
                ('clientType', models.CharField(blank=True, choices=[('Fizička osoba', 'Fizička osoba'), ('Pravna osoba', 'Pravna osoba')], max_length=40)),
                ('OIB', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'OIB mora sadržavati točno 11 broja.')])),
                ('SustavPDVa', models.BooleanField(default=False)),
                ('VATID', models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{13}$', 'Porezni identifikacijski broj mora sadržavati točno 13 karaktera, prva dva karaktera moraju biti identifikatori države, a ostalih 11 karaktera moraju biti brojevi koji označavaju entitet.')])),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('$', 'USD'), ('€', 'EUR'), ('£', 'GBP')], default='€', max_length=100)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(blank=True, max_length=200, null=True)),
                ('addressLine1', models.CharField(blank=True, max_length=200, null=True)),
                ('province', models.CharField(blank=True, choices=[('ZAGREBAČKA ŽUPANIJA', 'ZAGREBAČKA ŽUPANIJA'), ('KRAPINSKO-ZAGORSKA ŽUPANIJA', 'KRAPINSKO-ZAGORSKA ŽUPANIJA'), ('SISAČKO-MOSLAVAČKA ŽUPANIJA', 'SISAČKO-MOSLAVAČKA ŽUPANIJA'), ('KARLOVAČKA ŽUPANIJA', 'KARLOVAČKA ŽUPANIJA'), ('VARAŽDINSKA ŽUPANIJA', 'VARAŽDINSKA ŽUPANIJA'), ('KOPRIVNIČKO-KRIŽEVAČKA ŽUPANIJA', 'KOPRIVNIČKO-KRIŽEVAČKA ŽUPANIJA'), ('BJELOVARSKO-BILOGORSKA ŽUPANIJA', 'BJELOVARSKO-BILOGORSKA ŽUPANIJA'), ('PRIMORSKO-GORANSKA ŽUPANIJA', 'PRIMORSKO-GORANSKA ŽUPANIJA'), ('LIČKO-SENJSKA ŽUPANIJA', 'LIČKO-SENJSKA ŽUPANIJA'), ('VIROVITIČKO-PODRAVSKA ŽUPANIJA', 'VIROVITIČKO-PODRAVSKA ŽUPANIJA'), ('POŽEŠKO-SLAVONSKA ŽUPANIJA', 'POŽEŠKO-SLAVONSKA ŽUPANIJA'), ('BRODSKO-POSAVSKA ŽUPANIJA', 'BRODSKO-POSAVSKA ŽUPANIJA'), ('ZADARSKA ŽUPANIJA', 'ZADARSKA ŽUPANIJA'), ('OSJEČKO-BARANJSKA ŽUPANIJA', 'OSJEČKO-BARANJSKA ŽUPANIJA'), ('ŠIBENSKO-KNINSKA ŽUPANIJA', 'ŠIBENSKO-KNINSKA ŽUPANIJA'), ('VUKOVARSKO-SRIJEMSKA ŽUPANIJA', 'VUKOVARSKO-SRIJEMSKA ŽUPANIJA'), ('SPLITSKO-DALMATINSKA ŽUPANIJA', 'SPLITSKO-DALMATINSKA ŽUPANIJA'), ('ISTARSKA ŽUPANIJA', 'ISTARSKA ŽUPANIJA'), ('DUBROVAČKO-NERETVANSKA ŽUPANIJA', 'DUBROVAČKO-NERETVANSKA ŽUPANIJA'), ('MEĐIMURSKA ŽUPANIJA', 'MEĐIMURSKA ŽUPANIJA'), ('GRAD ZAGREB', 'GRAD ZAGREB'), ('INOZEMSTVO / NIJE PRIMJENJIVO', 'INOZEMSTVO / NIJE PRIMJENJIVO')], max_length=100)),
                ('postalCode', models.CharField(blank=True, max_length=5, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=40, null=True, validators=[arvelloapp.models.validate_phone_number])),
                ('emailAddress', models.CharField(blank=True, max_length=100, null=True)),
                ('clientUniqueId', models.CharField(blank=True, max_length=4, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Idetifikacijski broj klijenta mora sadržavati točno 4 broja.')])),
                ('clientType', models.CharField(blank=True, choices=[('Fizička osoba', 'Fizička osoba'), ('Pravna osoba', 'Pravna osoba')], max_length=40)),
                ('OIB', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'OIB mora sadržavati točno 11 broja.')])),
                ('VATID', models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{13}$', 'Porezni identifikacijski broj mora sadržavati točno 13 karaktera, prva dva karaktera moraju biti identifikatori države, a ostalih 11 karaktera moraju biti brojevi koji označavaju entitet.')])),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('dueDate', models.DateField(blank=True, null=True)),
                ('paymentTerms', models.CharField(choices=[('14 dana', '14 dana'), ('30 dana', '30 dana'), ('60 dana', '60 dana')], default='30 dana', max_length=100)),
                ('status', models.CharField(choices=[('Još nije plaćeno', 'Još nije plaćeno'), ('Dospijeće isteklo', 'Dospijeće isteklo'), ('Plaćeno', 'Plaćeno')], default='Još nije plaćeno', max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uniqueId', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arvelloapp.client')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arvelloapp.product')),
            ],
        ),
    ]
