# Generated by Django 4.2.8 on 2024-01-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arvelloapp', '0004_product_taxpercent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PozivNaBroj',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
