# Generated by Django 4.2.8 on 2024-01-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arvelloapp', '0005_product_pozivnabroj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='taxPercent',
            field=models.FloatField(blank=True, default=25, null=True),
        ),
    ]
