# Generated by Django 4.2.8 on 2024-01-16 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arvelloapp', '0006_alter_product_taxpercent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='paymentTerms',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='status',
        ),
    ]
