# Generated by Django 4.2.8 on 2024-01-16 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arvelloapp', '0007_remove_invoice_paymentterms_remove_invoice_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='PozivNaBroj',
        ),
    ]
