# Generated by Django 4.2.8 on 2024-02-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arvelloapp', '0009_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='VATID',
        ),
        migrations.AddField(
            model_name='settings',
            name='IBAN',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='SustavPDVa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
