# Generated by Django 4.2.8 on 2024-02-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arvelloapp', '0010_remove_settings_vatid_settings_iban_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
