# Generated by Django 4.2.8 on 2024-02-21 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arvelloapp', '0013_rename_settings_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arvelloapp.company'),
        ),
    ]
