# Generated by Django 4.2.8 on 2024-02-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arvelloapp', '0015_offer_date_offer_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='town',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
