# Generated by Django 4.2.8 on 2024-02-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arvelloapp', '0016_company_town'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='product',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='product',
        ),
        migrations.AddField(
            model_name='invoice',
            name='product',
            field=models.ManyToManyField(blank=True, to='arvelloapp.product'),
        ),
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ManyToManyField(blank=True, to='arvelloapp.product'),
        ),
    ]
