# Generated by Django 4.2.8 on 2024-03-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arvelloapp', '0018_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
