# Generated by Django 5.0.3 on 2024-04-02 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arvelloapp', '0022_remove_product_quantity_invoiceproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='product',
        ),
        migrations.RemoveField(
            model_name='invoiceproduct',
            name='total',
        ),
    ]
