# Generated by Django 5.0.3 on 2024-04-04 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arvelloapp', '0023_remove_invoice_product_remove_invoiceproduct_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='product',
        ),
        migrations.CreateModel(
            name='OfferProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arvelloapp.offer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arvelloapp.product')),
            ],
        ),
    ]
