# Generated by Django 5.0.3 on 2024-04-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arvelloapp', '0024_remove_offer_product_offerproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='made_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='made_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
