# Generated by Django 5.0.3 on 2024-04-05 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arvelloapp', '0025_invoice_made_by_offer_made_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='made_by',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='made_by',
        ),
    ]
