# Generated by Django 5.0.3 on 2024-04-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arvelloapp', '0026_remove_invoice_made_by_remove_offer_made_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceproduct',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='invoiceproduct',
            name='rabat',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
    ]
