# Generated by Django 5.0.3 on 2024-04-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arvelloapp', '0027_invoiceproduct_discount_invoiceproduct_rabat'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerproduct',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='offerproduct',
            name='rabat',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, null=True),
        ),
    ]
