# Generated by Django 5.0.3 on 2024-04-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arvelloapp', '0028_offerproduct_discount_offerproduct_rabat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
