# Generated by Django 5.0.3 on 2024-04-06 11:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arvelloapp', '0030_alter_invoice_number_alter_invoice_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='VATID',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{13}$', 'Porezni identifikacijski broj mora sadržavati točno 13 karaktera, prva dva karaktera moraju biti identifikatori države, a ostalih 11 karaktera moraju biti brojevi koji označavaju entitet.')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='addressLine1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='clientName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='clientType',
            field=models.CharField(choices=[('Fizička osoba', 'Fizička osoba'), ('Pravna osoba', 'Pravna osoba')], max_length=40),
        ),
        migrations.AlterField(
            model_name='client',
            name='clientUniqueId',
            field=models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Idetifikacijski broj klijenta mora sadržavati točno 4 broja.')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='emailAddress',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='postalCode',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='client',
            name='province',
            field=models.CharField(choices=[('ZAGREBAČKA ŽUPANIJA', 'ZAGREBAČKA ŽUPANIJA'), ('KRAPINSKO-ZAGORSKA ŽUPANIJA', 'KRAPINSKO-ZAGORSKA ŽUPANIJA'), ('SISAČKO-MOSLAVAČKA ŽUPANIJA', 'SISAČKO-MOSLAVAČKA ŽUPANIJA'), ('KARLOVAČKA ŽUPANIJA', 'KARLOVAČKA ŽUPANIJA'), ('VARAŽDINSKA ŽUPANIJA', 'VARAŽDINSKA ŽUPANIJA'), ('KOPRIVNIČKO-KRIŽEVAČKA ŽUPANIJA', 'KOPRIVNIČKO-KRIŽEVAČKA ŽUPANIJA'), ('BJELOVARSKO-BILOGORSKA ŽUPANIJA', 'BJELOVARSKO-BILOGORSKA ŽUPANIJA'), ('PRIMORSKO-GORANSKA ŽUPANIJA', 'PRIMORSKO-GORANSKA ŽUPANIJA'), ('LIČKO-SENJSKA ŽUPANIJA', 'LIČKO-SENJSKA ŽUPANIJA'), ('VIROVITIČKO-PODRAVSKA ŽUPANIJA', 'VIROVITIČKO-PODRAVSKA ŽUPANIJA'), ('POŽEŠKO-SLAVONSKA ŽUPANIJA', 'POŽEŠKO-SLAVONSKA ŽUPANIJA'), ('BRODSKO-POSAVSKA ŽUPANIJA', 'BRODSKO-POSAVSKA ŽUPANIJA'), ('ZADARSKA ŽUPANIJA', 'ZADARSKA ŽUPANIJA'), ('OSJEČKO-BARANJSKA ŽUPANIJA', 'OSJEČKO-BARANJSKA ŽUPANIJA'), ('ŠIBENSKO-KNINSKA ŽUPANIJA', 'ŠIBENSKO-KNINSKA ŽUPANIJA'), ('VUKOVARSKO-SRIJEMSKA ŽUPANIJA', 'VUKOVARSKO-SRIJEMSKA ŽUPANIJA'), ('SPLITSKO-DALMATINSKA ŽUPANIJA', 'SPLITSKO-DALMATINSKA ŽUPANIJA'), ('ISTARSKA ŽUPANIJA', 'ISTARSKA ŽUPANIJA'), ('DUBROVAČKO-NERETVANSKA ŽUPANIJA', 'DUBROVAČKO-NERETVANSKA ŽUPANIJA'), ('MEĐIMURSKA ŽUPANIJA', 'MEĐIMURSKA ŽUPANIJA'), ('GRAD ZAGREB', 'GRAD ZAGREB'), ('INOZEMSTVO / NIJE PRIMJENJIVO', 'INOZEMSTVO / NIJE PRIMJENJIVO')], max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='arvelloapp.client'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='arvelloapp.company'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='arvelloapp.client'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='arvelloapp.company'),
        ),
        migrations.AlterField(
            model_name='offerproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='barid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='taxPercent',
            field=models.FloatField(default=25),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
