# Generated by Django 5.0.6 on 2024-07-10 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arvelloapp', '0031_alter_client_vatid_alter_client_addressline1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='dueDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(6, 'Broj računa mora sadržavati više od 5 karaktera.')]),
        ),
    ]
