# Generated by Django 5.0.6 on 2024-07-10 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arvelloapp', '0033_alter_invoice_date_alter_invoice_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='dueDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='number',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(6, 'Broj računa mora sadržavati više od 5 karaktera.')]),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
