# Generated by Django 5.0.6 on 2024-07-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arvelloapp', '0034_alter_offer_date_alter_offer_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproduct',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, null=True),
        ),
    ]
