# Generated by Django 5.0.6 on 2024-08-31 15:27

import arvelloapp.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arvelloapp', '0035_alter_invoiceproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arvelloapp.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='IBAN',
            field=models.CharField(max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='addressLine1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='clientName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='clientType',
            field=models.CharField(choices=[('Fizička osoba', 'Fizička osoba'), ('Pravna osoba', 'Pravna osoba')], max_length=40),
        ),
        migrations.AlterField(
            model_name='company',
            name='clientUniqueId',
            field=models.CharField(max_length=4, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Idetifikacijski broj klijenta mora sadržavati točno 4 broja.')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='emailAddress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='phoneNumber',
            field=models.CharField(max_length=40, null=True, validators=[arvelloapp.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='company',
            name='postalCode',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='province',
            field=models.CharField(choices=[('ZAGREBAČKA ŽUPANIJA', 'ZAGREBAČKA ŽUPANIJA'), ('KRAPINSKO-ZAGORSKA ŽUPANIJA', 'KRAPINSKO-ZAGORSKA ŽUPANIJA'), ('SISAČKO-MOSLAVAČKA ŽUPANIJA', 'SISAČKO-MOSLAVAČKA ŽUPANIJA'), ('KARLOVAČKA ŽUPANIJA', 'KARLOVAČKA ŽUPANIJA'), ('VARAŽDINSKA ŽUPANIJA', 'VARAŽDINSKA ŽUPANIJA'), ('KOPRIVNIČKO-KRIŽEVAČKA ŽUPANIJA', 'KOPRIVNIČKO-KRIŽEVAČKA ŽUPANIJA'), ('BJELOVARSKO-BILOGORSKA ŽUPANIJA', 'BJELOVARSKO-BILOGORSKA ŽUPANIJA'), ('PRIMORSKO-GORANSKA ŽUPANIJA', 'PRIMORSKO-GORANSKA ŽUPANIJA'), ('LIČKO-SENJSKA ŽUPANIJA', 'LIČKO-SENJSKA ŽUPANIJA'), ('VIROVITIČKO-PODRAVSKA ŽUPANIJA', 'VIROVITIČKO-PODRAVSKA ŽUPANIJA'), ('POŽEŠKO-SLAVONSKA ŽUPANIJA', 'POŽEŠKO-SLAVONSKA ŽUPANIJA'), ('BRODSKO-POSAVSKA ŽUPANIJA', 'BRODSKO-POSAVSKA ŽUPANIJA'), ('ZADARSKA ŽUPANIJA', 'ZADARSKA ŽUPANIJA'), ('OSJEČKO-BARANJSKA ŽUPANIJA', 'OSJEČKO-BARANJSKA ŽUPANIJA'), ('ŠIBENSKO-KNINSKA ŽUPANIJA', 'ŠIBENSKO-KNINSKA ŽUPANIJA'), ('VUKOVARSKO-SRIJEMSKA ŽUPANIJA', 'VUKOVARSKO-SRIJEMSKA ŽUPANIJA'), ('SPLITSKO-DALMATINSKA ŽUPANIJA', 'SPLITSKO-DALMATINSKA ŽUPANIJA'), ('ISTARSKA ŽUPANIJA', 'ISTARSKA ŽUPANIJA'), ('DUBROVAČKO-NERETVANSKA ŽUPANIJA', 'DUBROVAČKO-NERETVANSKA ŽUPANIJA'), ('MEĐIMURSKA ŽUPANIJA', 'MEĐIMURSKA ŽUPANIJA'), ('GRAD ZAGREB', 'GRAD ZAGREB'), ('INOZEMSTVO / NIJE PRIMJENJIVO', 'INOZEMSTVO / NIJE PRIMJENJIVO')], max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='town',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
